import { Modal, setIcon } from "obsidian";
import type { App } from "obsidian";
import type { QuickAction } from "../models";
import { t } from "../i18n";

export class SlashMenuModal extends Modal {
  private readonly actions: QuickAction[]; private readonly initialQuery: string; private readonly onChoose: (action: QuickAction) => void; private readonly onClosed?: () => void; private readonly language: "en" | "nl"; private input!: HTMLInputElement; private list!: HTMLElement; private selected = 0;
  constructor(app: App, actions: QuickAction[], query: string, onChoose: (action: QuickAction) => void, onClosed?: () => void, language: "en" | "nl" = "en") { super(app); this.actions = actions; this.initialQuery = query; this.onChoose = onChoose; this.onClosed = onClosed; this.language = language; }
  onOpen(): void { this.modalEl.addClass("contextflow-slash-modal"); this.titleEl.setText(t("quickInsert", this.language)); this.contentEl.empty(); this.input = this.contentEl.createEl("input", { cls: "contextflow-search", attr: { type: "search", value: this.initialQuery, placeholder: t("searchActions", this.language), "aria-label": t("searchActions", this.language) } }); this.list = this.contentEl.createDiv({ cls: "contextflow-action-list", attr: { role: "listbox" } }); this.input.addEventListener("input", () => this.render()); this.input.addEventListener("keydown", (event) => this.keydown(event)); this.render(); window.setTimeout(() => this.input.focus(), 0); }
  onClose(): void { this.contentEl.empty(); this.onClosed?.(); }
  update(query: string, actions: QuickAction[]): void { this.input.value = query; this.actions.splice(0, this.actions.length, ...actions); this.render(); }
  private keydown(event: KeyboardEvent): void { if (event.key === "ArrowDown") { event.preventDefault(); this.selected = Math.min(this.selected + 1, this.filtered().length - 1); this.render(); } else if (event.key === "ArrowUp") { event.preventDefault(); this.selected = Math.max(0, this.selected - 1); this.render(); } else if (event.key === "Enter") { event.preventDefault(); const action = this.filtered()[this.selected]; if (action) { this.close(); this.onChoose(action); } } }
  private filtered(): QuickAction[] { const q = this.input?.value.toLocaleLowerCase() ?? ""; return this.actions.filter((action) => `${action.name} ${action.description}`.toLocaleLowerCase().includes(q)); }
  private render(): void { const actions = this.filtered(); this.selected = Math.min(this.selected, Math.max(0, actions.length - 1)); this.list.empty(); actions.slice(0, 12).forEach((action, index) => { const row = this.list.createDiv({ cls: `contextflow-action-row${index === this.selected ? " is-selected" : ""}` }); const icon = row.createSpan({ cls: "contextflow-action-icon" }); setIcon(icon, action.icon); row.createDiv({ cls: "contextflow-action-copy" }).createDiv({ cls: "contextflow-action-name", text: action.name }); row.addEventListener("mouseenter", () => { this.selected = index; this.render(); }); row.addEventListener("click", () => { this.close(); this.onChoose(action); }); }); if (!actions.length) this.list.createDiv({ cls: "contextflow-empty", text: t("noActions", this.language) }); }
}
